#!/usr/bin/env bash

echo "Updating plugins" &&
  git submodule init &&
  git submodule update &&
  git submodule foreach git pull origin master

cd bundle/elixir-ls
mix deps.get && mix compile
mix elixir_ls.release -o release
